version: '3'

services:

  database:
    image: mongo
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"

  nodejs:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 5050:5050
      - 9229:9229
